### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#10]
A feedback from teachers of pilot schools:
> Make it work in other common web browsers, not only Chrome. Firefox was mentioned by users several times.

**Comment by michzimny** [comment]
@Alfro, very soon, we would need to report on improvements done based on this feedback or, at least, what is our status regarding this. Would you be able to report in a few sentences if we find this improvement relevant and what can be the timeline to implement it?

**Comment by michzimny** [comment]
ping @Alfro

**Comment by michzimny** [comment]
@Alfro, do you consider to tackle this improvement request? If so, are you able to share any timeline that you consider?

**Comment by Alfro** [comment]
Hi @michzimny 

Sorry for the delay,
I am still discussing the development of this feature internally, but we will come with a timeline on adding support for Firefox soon. I'll keep you updated.

Best regards,

**Comment by ivanoterouvigo** [comment]
Hi everyone,
@Alfro, @vgoya 

Extension for Poddium not only with chrome if also for Firefox, at least.

There are many teachers and students that use firefox as main browser.

So I deeply suggest extensión for firefox browser.

![OnlywithChrome](https://user-images.githubusercontent.com/11814769/58756531-791aca00-84fa-11e9-88c9-27d881f64a06.png)

Regards

**Comment by Alfro** [comment]
@michzimny Both the staging and the prod instances just got Firefox support for the Personal Recorder.
