### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#12]
Please add Matomo tracking code to all pages of podium.eu as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

Please use the code for production instances.

**Comment by rubenrua** [comment]
Done

view-source:https://poddium.eu/
```
<script type="application/javascript" src="https://cdn.test.up2university.eu/scripts/matomo-production.js"></script>
```


We have also updated https://eduoer.up2university.eu/
