### ISSUE TITLE
LDAP service not enabled

### ISSUE THREAD

**Issue by andreacorleto** [teltek/PuMuKIT2-up2u-pr-bundle#14]
Launching Personal Recorder on test platform (https://learn.test.up2university.eu) gives back this error (see image attached).

I was trying to record a video lesson. When I launched Personal Recorder in the editor it displayed the message in the image.
![personal recorder-error-test-platform](https://user-images.githubusercontent.com/36439670/51898782-fd750900-23b1-11e9-8f1e-5b225c4c582f.jpg)

**Comment by Alfro** [comment]
Hi @andreacorleto 
Sorry for the inconvenience. We have found an issue with how some of the users were authenticating.

Could you try accessing the platform again?

**Comment by andreacorleto** [comment]
Now it's fine. Thanks
