### ISSUE TITLE
Do not publish videos by default

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#15]
Could we do not publish user-recorded video at poddium.eu by default, i.e. unless a user explicitly marks a video as public?

Are unpublished videos available to be used in Moodle?

CC @andreacorleto

**Comment by andreacorleto** [comment]
It seems to me that unpublished videos are not available to be used in moodle. The page displays an error message. Then, if you publish the video, this is available in moodle.
Other issue: video recorded through moodle are published by default in poddium.eu. To hide the video user must log on poddium.eu and change settings.

**Comment by michzimny** [comment]
Ok, so because of the privacy, we should probably change this behaviour to have:
* videos are not publicly available at poddium.eu by default
* videos are always accessible via Moodle by the user who own them

@rubenrua @pnieto, would it be feasible?

**Comment by Alfro** [comment]
Hi all, I think the platform should be correctly configured now.
Videos unpublished on WebTV may still be published, and thus accessible, on Moodle.

@andreacorleto I think the configuration may not have been marking videos as published on the correct platforms. Could you provide an id of the unpublished video that you mentioned before? I'll take a look at it and check if there was some mispublication.

Also, feel free to try uploading/recording new videos on the platform. Now it should not publish new videos on WebTV but they should still be accessible through Moodle.

**Comment by michzimny** [comment]
@Alfro, could we have unpublished videos (meaning: not publicly-visible at poddium.eu) but available to be used in Moodle? I think it's needed because of users' privacy. Users want to record something but share it with their students only, and not with everyone in the internet.

**Comment by Alfro** [comment]
@michzimny As I tried to explain on my previous comment, that's how the platform should be working right now. When you record something it is marked as:
* published on Moodle
* unpublished on poddium.eu

If that's not the case for you, please update this task, ideally with an id of the offending video.

**Comment by michzimny** [comment]
Ok, that's it. Thank you.
