### ISSUE TITLE
"The hash is not valid" in test Moodle

### ISSUE THREAD

**Issue by Callustian** [teltek/PuMuKIT2-up2u-pr-bundle#19]
The PR dialog recorder generates ( https://learn-dev.test.up2university.eu ):

There was an error. Please contact your administrator.
    Message: The hash is not valid.

Is this a similar problem to ( #8 )?

**Comment by Alfro** [comment]
This is a configuration issue. Solved manually and created issue on the moodle project to update the configuration scripts: https://github.com/up2university/docker-moodle/issues/166
