### ISSUE TITLE
Moodle issues

### ISSUE THREAD

**Issue by Callustian** [teltek/PuMuKIT2-up2u-pr-bundle#20]
Hello @Alfro ,

@ivanoterouvigo  tried the recorder and up2u and found several problems.
Then he created:

https://github.com/up2university/docker-moodle/issues/151
https://github.com/up2university/docker-moodle/issues/152
https://github.com/up2university/docker-moodle/issues/153
https://github.com/up2university/docker-moodle/issues/154
https://github.com/up2university/docker-moodle/issues/155
https://github.com/up2university/docker-moodle/issues/156

I apologise, I could not find the moodle settings to answer his requests.

Could you please suggest a solution for the issues?

Thanks.

**Comment by vgoya** [comment]
Thank you for adding those issues to this repository. We were not aware of them. Issues related with Poddium recorder should be filed here. and not where Ivan did. Ivan should move the issues here.

**Comment by Callustian** [comment]
No problem. Thank you for your message.

**Comment by vgoya** [comment]
My pleasure

**Comment by ivanoterouvigo** [comment]
Hello everyone,

@Callustian , @vgoya , @Alfro 

After my second testing of Poddium, I found several issues:

I've just moved to the right place and here you are:

[PuMuKIT2-up2u-pr-bundle/issues/22](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/22)
[PuMuKIT2-up2u-pr-bundle/issues/23](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/23)
[PuMuKIT2-up2u-pr-bundle/issues/24](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/24)
[PuMuKIT2-up2u-pr-bundle/issues/25](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/25)
[PuMuKIT2-up2u-pr-bundle/issues/26](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/26)
[PuMuKIT2-up2u-pr-bundle/issues/10](https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/10)

I hope this help.
Regards

**Comment by Alfro** [comment]
I am doing some maintenance of this repo issues. Currently, the issues still open from the originally reported are: 
https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/23
https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/25
https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/10

I am closing this issue as to not duplicate information. We will work on each issue separately.

I have also updated the moodle issues when relevant.

Regards,
