### ISSUE TITLE
eduOER and Moodle

### ISSUE THREAD

**Issue by Callustian** [teltek/PuMuKIT2-up2u-pr-bundle#21]
Hello @Alfro ,

Is it possible to have some more data about the structure of the system that makes use of eduOER and Moodle? I am collecting data that a software engineer could use should they have to add eduOER to some other Learning Management System.

Thanks,
Regards

**Comment by Alfro** [comment]
Hi @Callustian 
I think this issue should be opened on the eduOER project (https://github.com/up2university/eduoer/issues)

Could you also specify which kind of data are you looking for? The code relevant to eduOER can be found in the following repo, which includes the relevant Moodle module and PuMuKIT endpoint: https://github.com/teltek/PuMuKIT2-up2u-eduoer-bundle
