### ISSUE TITLE
Unexpected behavior after intalling extension Poddium

### ISSUE THREAD

**Issue by ivanoterouvigo** [teltek/PuMuKIT2-up2u-pr-bundle#22]
Hello everyone,
@vgoya , @Alfro 

First time you try to use Poddium you need to install the extensión, as you can see in the next image. (Poddium_000.png)

![Poddium_000](https://user-images.githubusercontent.com/11814769/58756019-381db800-84f0-11e9-937a-a14b8c389cf6.png)

After installing this extensión you are out of the moodle instances. Both production and test instances.

I think the expected behaviour could be:

**Option 1 )** Open new tab in order to install this extension.

or

**Option 2 )** Come back to moodle instance.

**Comment by Yurujai** [comment]
We have fixed this issue on stagging environment. 
It will be deployed to production soon.

**Comment by Alfro** [comment]
There is no need for the extension anymore, thus this issue is outdated now.
