### ISSUE TITLE
Change default configuration of video (From public to hide)

### ISSUE THREAD

**Issue by ivanoterouvigo** [teltek/PuMuKIT2-up2u-pr-bundle#24]
Hi everyone,
@vgoya , @Alfro 

When you begin to record yourselft, it is likely you don't want to publish the first demo videos.

So **I suggest** to change default configuration fo video from public to hide.

At least to **ask if you want to made the video public** or not after recording it.

Regards

**Comment by Yurujai** [comment]
Hi @ivanoterouvigo 

All videos generated by Personal Recorder and autopublisher user will be public videos but these videos arent published on Poddium.eu.

To show videos on Poddium.eu you should check the WebTV publication channel on the video publication preferences.

Regards.
