### ISSUE TITLE
Error after recording with Poddium as a Teacher in Production instance

### ISSUE THREAD

**Issue by ivanoterouvigo** [teltek/PuMuKIT2-up2u-pr-bundle#25]
Hi everyone,
@vgoya , @Alfro 

I found an error when you record a video and this video is directly load on the moodle space.
I've checked the test instance and it works fine but in the production platform it doesn't work.

Here you have the image.

![Error_showing_video_recording](https://user-images.githubusercontent.com/11814769/58756319-85048d00-84f6-11e9-9670-c21e8c020f3e.png)

Regards

**Comment by Alfro** [comment]
@ivanoterouvigo As mentioned in https://github.com/up2university/docker-moodle/issues/154 the issue does not seem to be reproducible anymore. I'm tentatively closing the issue.
