### ISSUE TITLE
If I change editor preferences, buttoms for accessing to EduOER and Poddium services don't appear.

### ISSUE THREAD

**Issue by ivanoterouvigo** [teltek/PuMuKIT2-up2u-pr-bundle#26]
Hi everyone,
@vgoya , @Alfro 

If I change editor preferences, buttoms for accessing to EduOER and Poddium services don't appear.

This happens when I change editor preferences. If I use any editor and this is not the default one, the buttoms for accessing to EduOER and Poddium don't appear.
I show you one image below.

![Poddium_002](https://user-images.githubusercontent.com/11814769/58756433-e3cb0600-84f8-11e9-9292-d1a2d044c297.png)

Regards

**Comment by Yurujai** [comment]
Hi @ivanoterouvigo 

The plugin is only available for the Atto editor. If you change the editor preferences you won't have  access to the EduOER and the Poddium plugins.

Regards.
