### ISSUE TITLE
Cannot embed video

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#3]
Steps to reproduce:
I follow the u2pu user guide for PR. In Moodle, I add Page content to a course. As a page content I choose PR icon and try to select already recorded video. I click the icon next to the video to publish it to LMS (see screenshot). 

![capture](https://user-images.githubusercontent.com/1483196/40713004-4c8e5208-63ff-11e8-810e-454fd04d1234.PNG)

What is expected: the video gets embedded in the page contents.

What happens: Nothing happens. The video is not embeded. An error appears in JS console:
```
ReferenceError: event is not defined[Learn More]
yui_combo.php:3:3625
_receiveMessage
https://learn.test.up2university.eu/theme/yui_combo.php:3:3625
_receiveMessage self-hosted:975:17 
```

I use the latest Firefox.

I use staging version of Moodle at https://learn.test.up2university.eu/

**Comment by Alfro** [comment]
@michzimny I can reproduce this error on Firefox, but not Chrome. I'll take a look at it, though.
In any case, can you confirm it works for you on Chrome?

**Comment by michzimny** [comment]
That's right. It works fine in Chrome.

**Comment by rubenrua** [comment]
Tested with Firefox 69.0b9 (64-bit) in macOS. 

* Site: https://learn.test.up2university.eu
* Course: "test 1" https://learn.test.up2university.eu/course/view.php?id=8
* Resource: https://learn.test.up2university.eu/mod/page/view.php?id=2166&forceview=1

![Screenshot_2019-07-31 Editing Page(3)](https://user-images.githubusercontent.com/195745/62225454-bf848c00-b3b8-11e9-8f7b-d95e8d3573d4.png)

![Screenshot_2019-07-31 Editing Page(4)](https://user-images.githubusercontent.com/195745/62225468-c57a6d00-b3b8-11e9-93a0-870709aeef7d.png)
