### ISSUE TITLE
Problem installing the Chrome extension

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#4]
If you don't have the right extension you see:
![pr](https://user-images.githubusercontent.com/1483196/41396280-b13720b0-6fb0-11e8-8f5d-25162aeb086e.png)

However, nothing happens after clicking the extension name. Other users have reported that too.

I think it has worked earlier.

**Comment by michzimny** [comment]
It still persists. Checked in Google Chrome on Windows and on Mac.

**Comment by Alfro** [comment]
Hi @michzimny, the Personal Recorder environments have been recently updated. Could you check if the issue still persists?

**Comment by michzimny** [comment]
It's fine now, thanks.
