### ISSUE TITLE
I can't use Personal Recorder

### ISSUE THREAD

**Issue by IlariaPhD** [teltek/PuMuKIT2-up2u-pr-bundle#5]
I tried to use PR from Up2U Moodle platform, but I can't see the camera button on the contents section to be filled when I add 'file' resource (I followed the instruction written in the User Guide document).
I tried with Mozilla Firefox and also Google Chrome, but I end up with the same result (see the picture).

![immagine](https://user-images.githubusercontent.com/43062324/45208466-f0347200-b28a-11e8-9314-010b94c4aa85.png)

**Comment by michzimny** [comment]
It seems to be fixed. The issue was lack of changes coming from https://github.com/up2university/docker-moodle/pull/79

**Comment by Alfro** [comment]
Doing some housekeeping. Closing the issue.
