### ISSUE TITLE
Problems in the visualization of videos created with PR

### ISSUE THREAD

**Issue by IlariaPhD** [teltek/PuMuKIT2-up2u-pr-bundle#6]
I can't visualize anymore contents uploaded on a Course and created with Personal Recorder.
The message in the picture below occours.

![immagine](https://user-images.githubusercontent.com/43062324/45210480-07c22980-b290-11e8-8371-f86d3eb9c2ea.png)

I tried with different browsers, but it's the same!

Important: I logged-in with the same credentials I used when I could see the video

**Comment by michzimny** [comment]
It seems to be fixed. The issue was lack of changes coming from https://github.com/up2university/docker-moodle/pull/79

**Comment by Alfro** [comment]
Doing some housekeeping. I'll close the issue.
