### ISSUE TITLE
ERROR: There was an error uploading the recording.

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#7]
In test Moodle, connected to pre-naked-pr-up2u.teltek.es, I'm getting "ERROR: There was an error uploading the recording." when clicking "Save" after video recording. Clicking "retry" does not help either.

**Comment by michzimny** [comment]
It might be related: HTTP request to pre-naked-pr-up2u.teltek.es returns:
```
301 Moved Permanently
Location: https://naked-pr-up2u.teltek.es/
```

Shoudn't it be: `Location: https://pre-naked-pr-up2u.teltek.es/`?

**Comment by Alfro** [comment]
Hello @michzimny 

Noted, we will take a look at it.

**Comment by Alfro** [comment]
Hi @michzimny , could you take a second look?

**Comment by michzimny** [comment]
It's fine now, thanks.
