### ISSUE TITLE
"The hash is not valid" in production Moodle

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#8]
I'm getting the following error when opening PR popup in the production Moodle:
> There was an error. Please contact your administrator.
> Message: The hash is not valid.

I'm sending now the production Moodle configuration to check the PR-related settings.

**Comment by Alfro** [comment]
Hi @michzimny, there might be an issue with some of the settings. Could you check the e-mail I sent you about it?

**Comment by Alfro** [comment]
Hello @michzimny , were you able to take a look at this?

**Comment by michzimny** [comment]
@Alfro, thanks. It works now since I corrected the settings. It was a Moodle configuration problem and I've reported in on the Moodle side: https://github.com/up2university/docker-moodle/issues/101
