### ISSUE TITLE
PR as a standalone tool for Up2U

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#9]
Enable ability to use it not only from Moodle, but also as a standalone tool (directly through its website).

This would prebable require an integration between PR and the Up2U SSO (https://github.com/up2university/single-sign-on).

This issue is based on a feedback from teachers.

**Comment by michzimny** [comment]
@Alfro, very soon, we would need to report on improvements done based on this feedback or, at least, what is our status regarding this. Would you be able to report in a few sentences if we find this improvement relevant and what can be the timeline to implement it?

Or pehaps you already have any achievements regarding the integration with Up2U SSO that could be reported?

**Comment by michzimny** [comment]
https://poddium.eu/ - is it considered done?

**Comment by Alfro** [comment]
Hi @michzimny 
Yes, we have already set-up the SSO integration. Poddium can be used now as a standalone tool, but we are still improving the UI to make it more intuitive for users to be used.

**Comment by Alfro** [comment]
Hey @michzimny 
I think this issue is obsolete now.
